fint:
  full-sync:
    initial-delay: 120000
    fixed-delay: 86400000
  adapter:
    username:
    password:
    id: https://fintlabs.no/ressurs/vams
    base-url: https://beta.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval-in-minutes: 3
    capabilities:
      digitalenhet:
        domain-name: ressurs
        packageName: datautstyr
        resource-name: digitalenhet
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      enhetsgruppe:
        domain-name: ressurs
        packageName: datautstyr
        resource-name: enhetsgruppe
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      enhetsgruppemedlemskap:
        domain-name: ressurs
        packageName: datautstyr
        resource-name: enhetsgruppemedlemskap
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      enhetstype:
        domain-name: ressurs
        packageName: kodeverk
        resource-name: enhetstype
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      plattform:
        domain-name: ressurs
        packageName: kodeverk
        resource-name: plattform
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      status:
        domain-name: ressurs
        packageName: kodeverk
        resource-name: status
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id: ${fint.adapter.client-id}
            client-secret: ${fint.adapter.client-secret}
            provider: fint-idp
            scope: fint-adapter
vams:
  client:
    county-code: OFK
    base-url: "https://vamsws.viken.no/ords/vams/expws/eiendeler/"
    grant-type: client_credentials
