fint:
  cron: "0 0 1 * * *"
  adapter:
    id: https://fintlabs.no/ressurs
    base-url: https://beta.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 3
    capabilities:
      digitalEnhet:
        domain-name: ressurs
        packageName: datautstyr
        resource-name: digitalEnhet
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      Enhetsgruppe:
        domain-name: ressurs
        packageName: datautstyr
        resource-name: Enhetsgruppe
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      Enhetstype:
        domain-name: ressurs
        packageName: datautstyr
        resource-name: Enhetstype
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      Status:
        domain-name: ressurs
        packageName: kodeverk
        resource-name: status
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      produsent:
        domain-name: ressurs
        packageName: kodeverk
        resource-name: produsent
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE